<a href="https://colab.research.google.com/github/Projas-14/Inteligencia_artificial/blob/master/Clasificaci%C3%B3n_de_flores_Iris_(scikit_learn).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clasificación de Flores Iris usando scikit-learn

**Descripción del Proyecto:**
En este proyecto, se creara un clasificador de flores Iris utilizando el conjunto de datos clásico de Iris. Este es un proyecto de clasificación simple ayudará a familiariza con la biblioteca scikit-learn y los conceptos básicos de machine learning.

## Preparación del Entorno:

Importa las bibliotecas necesarias, como numpy, pandas, scikit-learn.
Importa el conjunto de datos de Iris desde scikit-learn.

In [1]:
# Importar las bibliotecas necesarias
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Cargar el conjunto de datos Iris
iris = load_iris()

## Exploración de Datos:

Explora el conjunto de datos para comprender su estructura y las características de las flores Iris.
Visualiza las características de las flores usando gráficos como scatter plots o pair plots.

In [2]:
# Crear un DataFrame de Pandas para explorar los datos
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target

# Mostrar las primeras filas del DataFrame
iris_df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## Preprocesamiento de Datos:

Se dividira el conjunto de datos en características (X) y etiquetas (y).
Divide el conjunto de datos en conjuntos de entrenamiento y prueba usando train_test_split.

In [3]:
# Dividir el conjunto de datos en características (X) y etiquetas (y)
X = iris.data
y = iris.target

# Dividir los datos en conjuntos de entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## Entrenamiento del Modelo:

Se elige un algoritmo de clasificación simple, como el clasificador de vecinos más cercanos (K-Nearest Neighbors).
Entrena el modelo utilizando el conjunto de entrenamiento.

In [4]:
# Entrenar el modelo KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)


KNeighborsClassifier()

## Evaluación del Modelo:

Realiza predicciones sobre el conjunto de prueba.
Evalúa el rendimiento del modelo utilizando métricas como precisión, recall y F1-score.
Visualiza la matriz de confusión para entender mejor el rendimiento del modelo.

In [5]:
# Realizar predicciones sobre el conjunto de prueba
y_pred = knn.predict(X_test)

# Evaluar el rendimiento del modelo
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Matriz de confusión:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Optimización del Modelo:

Experimenta con diferentes algoritmos de clasificación y ajusta los hiperparámetros para mejorar el rendimiento del modelo.

Por ejemplo, podríamos probar un clasificador de árbol de decisiones y ajustar la profundidad máxima del árbol.

In [6]:
# Entrenar un clasificador de árbol de decisiones
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(max_depth=3)
dt_classifier.fit(X_train, y_train)

# Realizar predicciones sobre el conjunto de prueba
y_pred_dt = dt_classifier.predict(X_test)

# Evaluar el rendimiento del modelo
print("Clasificación de árbol de decisiones:\n", classification_report(y_test, y_pred_dt))
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred_dt))


Clasificación de árbol de decisiones:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Matriz de confusión:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Despliegue del Modelo (Opcional)
Podemos guardar el modelo entrenado para su uso futuro y crear una interfaz simple para que los usuarios ingresen características de una flor y obtengan la predicción del modelo.

In [7]:
# Guardar el modelo entrenado
import joblib
joblib.dump(knn, 'iris_model.pkl')

# Interfaz para predecir la clase de una flor Iris
def predict_flower():
    sepal_length = float(input("Ingrese la longitud del sépalo (cm): "))
    sepal_width = float(input("Ingrese el ancho del sépalo (cm): "))
    petal_length = float(input("Ingrese la longitud del pétalo (cm): "))
    petal_width = float(input("Ingrese el ancho del pétalo (cm): "))

    # Preprocesar los datos de entrada
    features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])

    # Cargar el modelo entrenado y hacer una predicción
    loaded_model = joblib.load('iris_model.pkl')
    prediction = loaded_model.predict(features)

    # Mapear el resultado de la predicción al nombre de la clase
    target_names = iris.target_names
    predicted_class = target_names[prediction[0]]

    print("La clase de la flor Iris es:", predicted_class)

# Ejecutar la función de predicción
predict_flower()


Ingrese la longitud del sépalo (cm): 10
Ingrese el ancho del sépalo (cm): 20
Ingrese la longitud del pétalo (cm): 20
Ingrese el ancho del pétalo (cm): 20
La clase de la flor Iris es: virginica


Ahora tienes un modelo optimizado (en este caso, un clasificador de árbol de decisiones) y una interfaz simple para que los usuarios ingresen características de una flor Iris y obtengan la predicción del modelo.